version: '3'

services:
  ecg_app:
    build:
        dockerfile: ecg_app/Dockerfile
    ports:
      - 8001:8001

  ecg_streamlit:
    build: 
        dockerfile: ecg_streamlit/Dockerfile
    ports:
      - 8501:8501
    depends_on:
      - ecg_app